### ISSUE TITLE
Nullzeilen in einzelnen Replicaten

### ISSUE THREAD

**Issue by TineLim** [datascience-mobi-2023/topic01_team04#6]
wenn jedes Replicate in der Rnase Probe eine Nullzeile hat, soll diese Protein, obwohl in der Kontrolle alles passt verworfen werden?
Kann aufjedenfall nicht gleich behandelt werden. Wieso passiert so etwas (auf wet lab bezogen)

**Comment by Anastasia933** [comment]
Ich glaube, du bist im falschen Projekt :) wir machen Image recognition!
